Q1

In [ ]:
 import numpy as np

 arr = np.array([1, 2, 3, 6, 4, 5])
 print(arr)
 rarr= np.flip(arr)
 print(rarr)

[1 2 3 6 4 5]
[5 4 6 3 2 1]


In [ ]:
import numpy as np

array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print(array1)

array2= array1.flatten()
print(array2)

[[1 2 3]
 [2 4 5]
 [1 2 3]]
[1 2 3 2 4 5 1 2 3]


In [ ]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

comp= arr1==arr2
print(comp)
equal=comp.all()
print("Array are ",equal)

[[ True  True]
 [ True  True]]
Array are  True


In [ ]:
import numpy as np
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
count= np.bincount(x)
count1= np.bincount(y)
print(count)
print(count1)
print("x",np.argmax(count))
print("y",np.argmax(count1))


[0 5 2 1 1 1]
[0 3 2 3 2]
x 1
y 1


In [ ]:
import numpy as np
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
row=np.sum(gfg, axis=1)
col=np.sum(gfg, axis=0)
s=np.sum(gfg)
print(s)
print("row",row)
print("col",col)

45
row [[14]
 [16]
 [15]]
col [[20  9 16]]


In [ ]:
import numpy as np
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
np.trace(n_array)


176

In [ ]:
import numpy as np
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
np.linalg.eig(n_array)

EigResult(eigenvalues=array([98.16835147, 28.097044  , 49.73460452]), eigenvectors=array([[ 0.4574917 ,  0.34637121, -0.15017693],
       [ 0.28447814, -0.72784061, -0.4852124 ],
       [ 0.84248058,  0.59184038,  0.8614034 ]]))

In [ ]:
import numpy as np
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
np.linalg.inv(n_array)


array([[ 0.02404141, -0.00911212, -0.00444671],
       [-0.01667882,  0.02966905,  0.0024785 ],
       [ 0.00631287, -0.01603732,  0.01217379]])

In [ ]:
import numpy as np
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
np.linalg.det(n_array)

137180.0000000001

In [ ]:
import numpy as np
p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]] )
np.matmul(p,q)


array([[16, 19],
       [26, 31]])

In [ ]:
import numpy as np
p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]] )
np.cov(p,q)

array([[0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5]])

In [ ]:
import numpy as np
p=np.array([[1, 2], [2, 3], [4, 5]])
q = np.array([[4, 5, 1], [6, 7, 2]])
np.matmul(p,q)

array([[16, 19,  5],
       [26, 31,  8],
       [46, 55, 14]])

In [ ]:
import numpy as np
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

print("inner",np.inner(x,y))
print("outer",np.outer(x,y))
print("cross",np.cross(x,y))

inner [[17 52]
 [13 62]]
outer [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
cross [[-20   4   7]
 [-84  36  20]]


Q2


In [ ]:
 import numpy as np
 array = np.array([[1, -2, 3],[-4, 5, -6]])
 np.absolute(array)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
 import numpy as np
 array = np.array([[1, -2, 3],[-4, 5, -6]])
 print(np.percentile(array,25))
 print( np.percentile(array,50))
 print(np.percentile(array,75))

-3.5
-0.5
2.5


In [ ]:
 import numpy as np
 array = np.array([[1, -2, 3],[-4, 5, -6]])
 print(np.mean(array))
 print(np.median(array))
 print(np.std(array))

-0.5
-0.5
3.8622100754188224


In [ ]:
import numpy as np
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
print(np.floor(a))
print(np.ceil(a))
print(np.trunc(a))
print(np.round(a))

[-2. -2. -1.  0.  1.  1.  3.]
[-1. -1. -0.  1.  2.  2.  3.]
[-1. -1. -0.  0.  1.  1.  3.]
[-2. -2. -0.  0.  2.  2.  3.]


Q3

In [ ]:
import numpy as np
array = np.array([10, 52, 62, 16, 16, 54, 453])
print(np.sort(array))
print(np.argsort(array))
tarr=np.sort(array)
tarrr=np.sort(array)[::-1]
print(tarr[0:4])
print(tarrr[0:5])


[ 10  16  16  52  54  62 453]
[0 3 4 1 5 2 6]
[10 16 16 52]
[453  62  54  52  16]


In [ ]:
 import numpy as np
 array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
 print(array.astype(int))
 print(array.astype(np.float64))

[1 1 2 2 3 2]
[1.  1.2 2.2 2.  3.  2. ]


Q4

In [7]:
from PIL import Image
import numpy as np

def img_to_array(path):
    # Load the image
    img = Image.open(path)

    # Convert image to numpy array
    img_array = np.array(img)

    # Determine if the image is RGB or Grayscale
    if len(img_array.shape) == 3:  # RGB image
        file_name = path.split('.')[0] + '_rgb.txt'
        # Flatten the array and save it
        with open(file_name, 'w') as f:
            for row in img_array:
                np.savetxt(f, row, fmt='%d', newline=' ')
                f.write('\n')
    elif len(img_array.shape) == 2:  # Grayscale image
        file_name = path.split('.')[0] + '_gray.txt'
        # Flatten the array and save it
        with open(file_name, 'w') as f:
            np.savetxt(f, img_array, fmt='%d', newline=' ')
            f.write('\n')
    else:
        raise ValueError("Unsupported image format")

    print(f"Image data has been saved to {file_name}")


